services:
  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: msdis-kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAME: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - msdis-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # PostgreSQL service
  postgres:
    image: postgres:16-alpine
    container_name: msdis-postgres
    hostname: postgres
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - msdis-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d events"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msdis-app
    hostname: app
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      UsePostgreSQL: "true"
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: user-events
      KAFKA_GROUP_ID: msdis-consumer
      POSTGRES_CONNECTION_STRING: "Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=events"
      FILE_STORAGE_PATH: user_event_stats.json
    ports:
      - "8080:8080"
    volumes:
      - ./user_event_stats.json:/app/user_event_stats.json
    networks:
      - msdis-network
    restart: unless-stopped

# Networks
networks:
  msdis-network:
    driver: bridge

# Volumes
volumes:
  pgdata:
    driver: local
  kafka_data:
    driver: local


